openapi: 3.0.0
info:
  title: autodeskAPI
  version: 1.0.0
servers:
  - url: https://developer.api.autodesk.com
  - url: http://{{contentuploadsignedurl}}
paths:
  /authentication/v1/authenticate:
    post:
      tags:
        - General
      summary: Get an Access Token
      description: >-
        [See
        Documentation](https://aps.autodesk.com/en/docs/oauth/v2/reference/http/authenticate-POST/)
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                client_id:
                  type: string
                  example: '{{client_id}}'
                client_secret:
                  type: string
                  example: '{{client_secret}}'
                grant_type:
                  type: string
                  example: client_credentials
                scope:
                  type: string
                  example: >-
                    code:all data:write data:read bucket:create bucket:delete
                    bucket:read
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/x-www-form-urlencoded
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /oss/v2/buckets:
    post:
      tags:
        - General
      summary: Create a Bucket
      description: >-
        [See
        documentation](https://aps.autodesk.com/en/docs/data/v2/reference/http/buckets-POST/)
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: >-
                "{\n\t\"bucketKey\": \"{{ossBucketKey}}\",\n\t\"policyKey\":
                \"transient\"\n}\n"
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
        - name: Authorization
          in: header
          schema:
            type: string
          example: Bearer {{access_token}}
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /oss/v2/buckets/{ossBucketKey}/objects/{ossSourceFileObjectKey}/signeds3upload:
    get:
      tags:
        - General
      summary: Obtain Signed URL
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: Bearer {{access_token}}
        - name: minutesExpiration
          in: query
          schema:
            type: integer
          example: '5'
        - name: ossBucketKey
          in: path
          schema:
            type: string
          required: true
        - name: ossSourceFileObjectKey
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - General
      summary: Finalize upload
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: '"{\n    \"uploadKey\":\"{{UploadKey}}\"\n}"'
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: Bearer {{access_token}}
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
        - name: ossBucketKey
          in: path
          schema:
            type: string
          required: true
        - name: ossSourceFileObjectKey
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /:
    put:
      tags:
        - General
      summary: Upload the File
      requestBody:
        content:
          text/plain: {}
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /modelderivative/v2/designdata/formats:
    get:
      tags:
        - General
      summary: Get Supported Formats
      description: >-
        [See
        documentation](https://aps.autodesk.com/en/docs/model-derivative/v2/reference/http/formats-GET/)
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: Bearer {{access_token}}
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /oss/v2/buckets/{ossBucketKey}/details:
    get:
      tags:
        - General
      summary: Get Bucket Details
      description: >-
        [See
        documentation](https://aps.autodesk.com/en/docs/data/v2/reference/http/buckets-:bucketKey-details-GET/)
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: Bearer {{access_token}}
        - name: ossBucketKey
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /modelderivative/v2/designdata/job:
    post:
      tags:
        - General
      summary: Create a Translation Job
      description: >-
        [See
        documentation](https://aps.autodesk.com/en/docs/model-derivative/v2/reference/http/job-POST/)
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                input:
                  urn: '{{t1_ossEncodedSourceFileURN}}'
                output:
                  destination:
                    region: us
                  formats:
                    - type: obj
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
        - name: Authorization
          in: header
          schema:
            type: string
          example: Bearer {{access_token}}
        - name: x-ads-force-all
          in: header
          schema:
            type: boolean
          example: 'true'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /modelderivative/v2/designdata/{t1_url_safe_urn_of_source}/manifest:
    get:
      tags:
        - General
      summary: Check Status of Job
      description: >-
        [See
        documentation](https://aps.autodesk.com/en/docs/model-derivative/v2/reference/http/urn-manifest-GET/)
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: Bearer {{access_token}}
        - name: t1_url_safe_urn_of_source
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
